version: "3"
services:
  api:
    image: $DOCKERHUB_UNAME/djoser-tutorial_api-prod:$NEW_VERSION
    environment:
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - AWS_SES_REGION_NAME=$AWS_SES_REGION_NAME
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - DOMAIN=$DOMAIN
    depends_on:
      - db
  nginx:
    image: $DOCKERHUB_UNAME/djoser-tutorial_webserver-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
  db:
    image: postgres:15
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# volumes:
#   postgres_data: